# name: Backup Configuration files

# on: [ push ]
# permissions: 
#   contents: write

# jobs:
#   backup:
#     runs-on: ubuntu-24.04

#     steps:
#     - name: checkout repository
#       uses: actions/checkout@v4

#     - name: create backup folder
#       run: mkdir -p backup

#     - name: add config file to backup folder
#       run: cp -r configs/* backup/

#     - name: commit backup changes
#       run: |
#         git config user.name "github-actions"
#         git config user.email "github-actions@github.com"
#         git add backup
#         git commit -m "created folder and added file" || echo "no changes to commit"
#         git push
